on: 
  push:
    branches:
      - master**

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create GitHub release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease